vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
vim.keymap.set("n", "<leader>h", "<C-w>h")
vim.keymap.set("n", "<leader>j", "<C-w>j")
vim.keymap.set("n", "<leader>k", "<C-w>k")
vim.keymap.set("n", "<leader>l", "<C-w>l")
vim.keymap.set("n", ";", ":")
vim.keymap.set("n", "<leader>y", "\"+y")
vim.keymap.set("n", "<leader>gs", ":s/^pick/squash/<CR>")
vim.keymap.set("n", "<leader>mm", ":e ~/.config/nvim/lua/steovim/remap.lua")

vim.keymap.set("n", "L", "$")
vim.keymap.set("n", "H", "^")
